<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>8fabe5c3-e982-40e4-875a-98f5579d8545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Logout')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-logout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3eebcca-bd7e-485d-bb23-9f21b5d08c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://stage.caa.gov.qa/en/user/logout</value>
      <webElementGuid>1ebe1317-348d-4505-b230-ed361737f6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-logout</value>
      <webElementGuid>54cfae62-9c00-4208-9927-b63a867cb513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>ce683bdf-f135-4d66-bff9-76bc7a5f1658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js&quot;]/body[1]/div[@class=&quot;dialog-off-canvas-main-canvas&quot;]/header[@class=&quot;page-header clearfix&quot;]/div[@class=&quot;header-top&quot;]/div[@class=&quot;header-top__sm&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;header-top__right&quot;]/div[@class=&quot;dropdown-menu show&quot;]/div[@class=&quot;dropdown-menu__links&quot;]/a[@class=&quot;btn btn-logout&quot;]</value>
      <webElementGuid>5af14aed-fd5a-4c5d-922b-a488864a790b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
      <webElementGuid>cc954d13-b702-430d-97c0-5b14c1617ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/following::a[1]</value>
      <webElementGuid>cda29e53-6916-4621-a009-336616c6eb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MA'])[2]/following::a[2]</value>
      <webElementGuid>1cc27b1b-3be9-4c79-ac38-4ec2e93e6f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About QCAA'])[1]/preceding::a[2]</value>
      <webElementGuid>6fb7585d-96db-459c-bf40-0be2cf1afdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laws and Regulations'])[1]/preceding::a[3]</value>
      <webElementGuid>97e17313-9375-4ca0-b904-3a4fb93e0498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>3db93b41-f8e9-4093-9278-765761f61e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://stage.caa.gov.qa/en/user/logout')]</value>
      <webElementGuid>b7ca2940-b55b-4fd0-b132-69ffd6710efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/a</value>
      <webElementGuid>bdc08643-bec2-4106-a361-31b1bdb3e9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://stage.caa.gov.qa/en/user/logout' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>766ecac3-4f41-4b6e-b9d7-1934458017fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
